name: flutter_oschina
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  flutter_webview_plugin: ^0.3.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    # 导航栏图标
    - assets/images/ic_nav_discover_actived.png
    - assets/images/ic_nav_discover_normal.png
    - assets/images/ic_nav_my_normal.png
    - assets/images/ic_nav_my_pressed.png
    - assets/images/ic_nav_news_actived.png
    - assets/images/ic_nav_news_normal.png
    - assets/images/ic_nav_tweet_actived.png
    - assets/images/ic_nav_tweet_normal.png
    # 抽屉背景
    - assets/images/cover_img.jpg
    # 用户默认头像
    - assets/images/ic_avatar_default.png